export const routesConstants = {
  POSTS: 'posts',
  BLOGS: 'blogs',
  TESTING: 'testing',
  ALL_DATA: 'all-data',
  AUTH: 'auth',
  USERS: 'users',
  LOGIN: 'login',
  ME: 'me',
  COMMENTS: 'comments',
  REGISTRATION_CONFIRM: 'registration-confirmation',
  REGISTRATION_EMAIL_RESEND: 'registration-email-resending',
  REGISTRATION: 'registration',
  LOGOUT: 'logout',
  REFRESH_TOKEN: 'refresh-token',
  SECURITY: 'security',
  DEVICES: 'devices',
};
